* Updates for the checkinstall installation. * Installing the TUI documentation and skin files in Autopackage now. * Installing the libr3r.h file now (if R3R_UI=wx), to make it easier to create your own interfaces. * Expanded the descriptions in the TUI so that they'll be cut off when room stops, not at 150 characters. * Cut out some duplicate links in the RSS parser (I'm still trying to figure out the cause of the odd Atom links). * Fixed regression in caching support. * Fixed cut-off descriptions in XML-based feeds (using the version of the StrPas function from SysUtils instead of the one limited to 255 characters in the System unit). * Removed the automatic redrawing on resize when using nCRT, which caused more problems than it solved. * Fixed display of RDF-based RSS feeds. * Always installing libr3r.h * Moved ColorTableInit to TTui.Draw, so that new skins will take effect immediately. * Better path searching for DOS-based operating systems. * RedrawConditional readded to ScrollTo in the TUI.

diff --git a/r3r b/r3r
--- a/r3r
+++ b/r3r
@@ -1,5 +1,17 @@
 #! /bin/sh
 
+# Get the parent directory (for relocatability)
+curdir=`dirname $0`
+cd $curdir
+cwd=`pwd`
+curdir=`echo $curdir | sed -e "s|^\(\.\+\)|$cwd/\1|"`
+cd ..
+parentdir=`pwd`
+cd $curdir
+
+R3R_INSTALLED_PREFIX=$parentdir
+export R3R_INSTALLED_PREFIX
+
 # If there's an error
 err()
 {
@@ -17,7 +29,7 @@ err()
 # Start up the preferred UI if defined
 if test -n "$R3R_UI";
 then
-  r3r-$R3R_UI "$@"
+  ./r3r-$R3R_UI "$@"
 else
   false
 fi
@@ -25,5 +37,5 @@ fi
 # There was an error or no preferred UI is defined
 if test $? -ne 0;
 then
-  r3r-wx "$@" || r3r-tui "$@" || r3r-html "$@" || err "Cannot start any UI"
+  ./r3r-wx "$@" || ./r3r-tui "$@" || ./r3r-html "$@" || err "Cannot start any UI"
 fi
